---
- hosts: localhost
  tasks: 
    - name: create ec2 instance
      ec2:  
        key_name: awskey
        instance_type: t2.micro
        region: us-east-1
        image: ami-0c293f3f676ec4f90
        wait: yes
        count: 1
        vpc_subnet_id: subnet-052e42663fef2737f
        assign_public_ip: yes



